2020-04-06 21:26:54.632692 (MainThread): Running with dbt=0.16.0
2020-04-06 21:26:54.842887 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2020-04-06 21:26:54.866856 (MainThread): Tracking: tracking
2020-04-06 21:26:54.867620 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81c6e2e8>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81c77978>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81c77d68>]}
2020-04-06 21:26:54.867959 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=13
2020-04-06 21:26:54.868846 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2020-04-06 21:26:54.869287 (MainThread): Send requests to http://localhost:8580/jsonrpc
2020-04-06 21:26:54.871139 (Thread-1): Parsing macros/core.sql
2020-04-06 21:26:54.875928 (Thread-1): Parsing macros/adapters/common.sql
2020-04-06 21:26:54.927591 (Thread-1): Parsing macros/schema_tests/unique.sql
2020-04-06 21:26:54.928892 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2020-04-06 21:26:54.931026 (Thread-1): Parsing macros/schema_tests/not_null.sql
2020-04-06 21:26:54.932055 (Thread-1): Parsing macros/schema_tests/relationships.sql
2020-04-06 21:26:54.933352 (Thread-1): Parsing macros/materializations/helpers.sql
2020-04-06 21:26:54.941778 (Thread-1): Parsing macros/materializations/common/merge.sql
2020-04-06 21:26:54.955135 (Thread-1): Parsing macros/materializations/table/table.sql
2020-04-06 21:26:54.961954 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2020-04-06 21:26:54.968452 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2020-04-06 21:26:54.970524 (Thread-1): Parsing macros/materializations/seed/seed.sql
2020-04-06 21:26:54.992013 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2020-04-06 21:26:55.009465 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2020-04-06 21:26:55.049947 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-04-06 21:26:55.053099 (Thread-1): Parsing macros/materializations/view/view.sql
2020-04-06 21:26:55.061254 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2020-04-06 21:26:55.069330 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2020-04-06 21:26:55.072700 (Thread-1): Parsing macros/etc/is_incremental.sql
2020-04-06 21:26:55.074448 (Thread-1): Parsing macros/etc/get_custom_database.sql
2020-04-06 21:26:55.075578 (Thread-1): Parsing macros/etc/datetime.sql
2020-04-06 21:26:55.086184 (Thread-1): Parsing macros/etc/get_relation_comment.sql
2020-04-06 21:26:55.088554 (Thread-1): Parsing macros/etc/query.sql
2020-04-06 21:26:55.089709 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2020-04-06 21:26:55.091226 (Thread-1): Parsing macros/catalog.sql
2020-04-06 21:26:55.099410 (Thread-1): Parsing macros/etc.sql
2020-04-06 21:26:55.100208 (Thread-1): Parsing macros/adapters.sql
2020-04-06 21:26:55.128769 (Thread-1): Parsing macros/materializations/view.sql
2020-04-06 21:26:55.131458 (Thread-1): Parsing macros/materializations/incremental.sql
2020-04-06 21:26:55.148375 (Thread-1): Parsing macros/materializations/table.sql
2020-04-06 21:26:55.161227 (Thread-1): Parsing macros/materializations/seed.sql
2020-04-06 21:26:55.164681 (Thread-1): Parsing macros/materializations/snapshot.sql
2020-04-06 21:26:55.528758 (Thread-1): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 4 unused configuration paths:
- models.github_edw.source
- models.github_edw.stage
- models.github_edw.dw
- models.github_edw

2020-04-06 21:26:55.982314 (Thread-2): handling status request
2020-04-06 21:26:55.982925 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81308208>]}
2020-04-06 21:26:55.990613 (Thread-2): sending response (<Response 9376 bytes [200 OK]>) to 10.0.5.66
2020-04-06 21:33:56.309966 (Thread-3): handling status request
2020-04-06 21:33:56.312143 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812e0a90>]}
2020-04-06 21:33:56.317215 (Thread-3): sending response (<Response 9376 bytes [200 OK]>) to 10.0.5.66
2020-04-06 21:33:57.923712 (Thread-4): For key github, hash mismatch (FileHash(name='sha256', checksum='d5dbd74e4a31f4876112de6f6634db3132d59310d008996f5224a6c347fee5d1') -> FileHash(name='sha256', checksum='d89b6bb51ae3a1fc9b183e7968777575a0cde66ec60ffcfd37ed63d260879f64')), cache invalidated
2020-04-06 21:33:58.124536 (Thread-5): handling status request
2020-04-06 21:33:58.125213 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812be320>]}
2020-04-06 21:33:58.126279 (Thread-5): sending response (<Response 182 bytes [200 OK]>) to 10.0.27.197
2020-04-06 21:33:58.340226 (Thread-4): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 4 unused configuration paths:
- models.github.source
- models.github.dw
- models.github
- models.github.stage

2020-04-06 21:33:59.339576 (Thread-6): handling status request
2020-04-06 21:33:59.340273 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812f72b0>]}
2020-04-06 21:33:59.341448 (Thread-6): sending response (<Response 1139 bytes [200 OK]>) to 10.0.46.192
2020-04-06 21:35:27.589667 (Thread-7): Got an acceptable cached parse result
2020-04-06 21:35:27.650923 (Thread-7): Acquiring new bigquery connection "model.github.commits".
2020-04-06 21:35:27.651099 (Thread-7): Opening a new connection, currently in state init
2020-04-06 21:35:27.767057 (Thread-8): handling status request
2020-04-06 21:35:27.767661 (Thread-8): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8095d518>]}
2020-04-06 21:35:27.768657 (Thread-8): sending response (<Response 182 bytes [200 OK]>) to 10.0.23.84
2020-04-06 21:35:27.903335 (Thread-7): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.github.dw
- models.github.stage

2020-04-06 21:35:28.960865 (Thread-9): handling status request
2020-04-06 21:35:28.961376 (Thread-9): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8099b390>]}
2020-04-06 21:35:28.962616 (Thread-9): sending response (<Response 1448 bytes [200 OK]>) to 10.0.29.175
2020-04-06 21:36:51.941191 (Thread-10): handling run_sql request
2020-04-06 21:36:51.943612 (Thread-10): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c836849b0>]}
2020-04-06 21:36:51.946808 (Thread-10): Connection 'model.github.commits' was properly closed.
2020-04-06 21:36:51.952371 (Thread-10): sending response (<Response 133 bytes [200 OK]>) to 10.0.5.66
2020-04-06 21:36:51.967613 (Thread-10): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:36:51.968156 (Thread-10): Opening a new connection, currently in state init
2020-04-06 21:36:51.982591 (Thread-11): handling ps request
2020-04-06 21:36:51.983333 (Thread-11): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809c4860>]}
2020-04-06 21:36:51.986613 (Thread-11): sending response (<Response 397 bytes [200 OK]>) to 10.0.27.197
2020-04-06 21:36:51.982591 (Thread-10): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:36:51.983995 (Thread-11): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:36:51.984175 (Thread-11): Opening a new connection, currently in state init
2020-04-06 21:36:51.984327 (Thread-11): Compiling rpc.github.request
2020-04-06 21:36:52.006335 (Thread-11): finished collecting timing info
2020-04-06 21:36:52.007834 (Thread-11): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
select *
from bigquery-public-data.github_repos.commits
limit 100
2020-04-06 21:36:52.102141 (Thread-12): handling poll request
2020-04-06 21:36:52.102673 (Thread-12): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809a8828>]}
2020-04-06 21:36:52.106365 (Thread-12): sending response (<Response 3185 bytes [200 OK]>) to 10.0.7.248
2020-04-06 21:36:52.778576 (Thread-13): handling poll request
2020-04-06 21:36:52.779086 (Thread-13): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8099b710>]}
2020-04-06 21:36:52.780883 (Thread-13): sending response (<Response 3186 bytes [200 OK]>) to 10.0.23.84
2020-04-06 21:36:53.452610 (Thread-14): handling poll request
2020-04-06 21:36:53.453124 (Thread-14): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81390c18>]}
2020-04-06 21:36:53.454985 (Thread-14): sending response (<Response 3185 bytes [200 OK]>) to 10.0.9.254
2020-04-06 21:36:53.501944 (Thread-11): finished collecting timing info
2020-04-06 21:36:54.102808 (Thread-15): handling poll request
2020-04-06 21:36:54.103331 (Thread-15): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c813903c8>]}
2020-04-06 21:36:54.108734 (Thread-15): sending response (<Response 84548 bytes [200 OK]>) to 10.0.7.248
2020-04-06 21:44:04.532940 (Thread-16): handling ps request
2020-04-06 21:44:04.535006 (Thread-16): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81310be0>]}
2020-04-06 21:44:04.535788 (Thread-16): sending response (<Response 100 bytes [200 OK]>) to 10.0.5.66
2020-04-06 21:44:04.579376 (Thread-17): handling run_sql request
2020-04-06 21:44:04.579849 (Thread-17): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c813105c0>]}
2020-04-06 21:44:04.586250 (Thread-17): sending response (<Response 133 bytes [200 OK]>) to 10.0.39.229
2020-04-06 21:44:04.600754 (Thread-17): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:44:04.601308 (Thread-17): Opening a new connection, currently in state init
2020-04-06 21:44:04.613728 (Thread-17): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:44:04.614841 (Thread-18): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:44:04.614961 (Thread-18): Opening a new connection, currently in state init
2020-04-06 21:44:04.615067 (Thread-18): Compiling rpc.github.request
2020-04-06 21:44:04.631306 (Thread-18): finished collecting timing info
2020-04-06 21:44:04.633799 (Thread-18): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
FROM
  bigquery-public-data.github_repos.commits;
limit 100
2020-04-06 21:44:04.784722 (Thread-18): handling poll request
2020-04-06 21:44:04.785290 (Thread-18): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81390208>]}
2020-04-06 21:44:04.787768 (Thread-18): sending response (<Response 3485 bytes [200 OK]>) to 10.0.27.197
2020-04-06 21:44:04.905812 (Thread-18): finished collecting timing info
2020-04-06 21:44:04.906508 (Thread-18): Got an exception: Database Error
  Syntax error: Unexpected keyword LIMIT at [17:1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword LIMIT at [17:1]

(job ID: dc8a6ec7-287b-4f1f-931c-490414cb8b61)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:SELECT
   3:  commit,
   4:  tree,
   5:  parent,
   6:  author.name author_name,
   7:  author.email author_email,
   8:  author.date.seconds author_date_seconds,
   9:  committer.name committer_name,
  10:  committer.email committer_email,
  11:  committer.date.seconds committer_date_seconds,
  12:  subject,
  13:  message,
  14:  repo_name
  15:FROM
  16:  bigquery-public-data.github_repos.commits;
  17:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unexpected keyword LIMIT at [17:1]
2020-04-06 21:44:04.908782 (Thread-18): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword LIMIT at [17:1]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\nFROM\n  bigquery-public-data.github_repos.commits;\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\nFROM\n  bigquery-public-data.github_repos.commits;\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword LIMIT at [17:1]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\nFROM\n  bigquery-public-data.github_repos.commits;\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\nFROM\n  bigquery-public-data.github_repos.commits;\nlimit 100', 'tags': None}, None)
2020-04-06 21:44:05.514938 (Thread-19): handling poll request
2020-04-06 21:44:05.515437 (Thread-19): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81395b00>]}
2020-04-06 21:44:05.516351 (Thread-19): sending response (<Response 11817 bytes [200 OK]>) to 10.0.7.248
2020-04-06 21:44:20.234304 (Thread-20): handling run_sql request
2020-04-06 21:44:20.236658 (Thread-20): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81391f28>]}
2020-04-06 21:44:20.242485 (Thread-20): sending response (<Response 133 bytes [200 OK]>) to 10.0.46.192
2020-04-06 21:44:20.247595 (Thread-21): handling ps request
2020-04-06 21:44:20.248086 (Thread-21): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809cb240>]}
2020-04-06 21:44:20.249927 (Thread-21): sending response (<Response 399 bytes [200 OK]>) to 10.0.9.254
2020-04-06 21:44:20.257058 (Thread-20): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:44:20.257519 (Thread-20): Opening a new connection, currently in state init
2020-04-06 21:44:20.264769 (Thread-20): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:44:20.265664 (Thread-21): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:44:20.265778 (Thread-21): Opening a new connection, currently in state init
2020-04-06 21:44:20.266028 (Thread-21): Compiling rpc.github.request
2020-04-06 21:44:20.279100 (Thread-21): finished collecting timing info
2020-04-06 21:44:20.280509 (Thread-21): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
FROM
  bigquery-public-data.github_repos.commits
limit 100
2020-04-06 21:44:20.417940 (Thread-22): handling poll request
2020-04-06 21:44:20.418465 (Thread-22): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809cbe48>]}
2020-04-06 21:44:20.420337 (Thread-22): sending response (<Response 3484 bytes [200 OK]>) to 10.0.39.229
2020-04-06 21:44:21.103916 (Thread-23): handling poll request
2020-04-06 21:44:21.104447 (Thread-23): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809a4b00>]}
2020-04-06 21:44:21.106275 (Thread-23): sending response (<Response 3484 bytes [200 OK]>) to 10.0.29.175
2020-04-06 21:44:21.814604 (Thread-21): finished collecting timing info
2020-04-06 21:44:21.818066 (Thread-24): handling poll request
2020-04-06 21:44:21.818574 (Thread-24): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81343240>]}
2020-04-06 21:44:21.820462 (Thread-24): sending response (<Response 3895 bytes [200 OK]>) to 10.0.9.254
2020-04-06 21:44:22.494870 (Thread-25): handling poll request
2020-04-06 21:44:22.495380 (Thread-25): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81391cc0>]}
2020-04-06 21:44:22.500734 (Thread-25): sending response (<Response 58852 bytes [200 OK]>) to 10.0.27.197
2020-04-06 21:56:54.024975 (Thread-26): handling compile_sql request
2020-04-06 21:56:54.027030 (Thread-26): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8131c7f0>]}
2020-04-06 21:56:54.033495 (Thread-26): sending response (<Response 133 bytes [200 OK]>) to 10.0.9.254
2020-04-06 21:56:54.035583 (Thread-27): handling ps request
2020-04-06 21:56:54.037620 (Thread-27): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8131c7f0>]}
2020-04-06 21:56:54.039807 (Thread-27): sending response (<Response 406 bytes [200 OK]>) to 10.0.13.188
2020-04-06 21:56:54.049163 (Thread-26): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:56:54.049658 (Thread-26): Opening a new connection, currently in state init
2020-04-06 21:56:54.061219 (Thread-26): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:56:54.062193 (Thread-27): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:56:54.062314 (Thread-27): Opening a new connection, currently in state init
2020-04-06 21:56:54.062430 (Thread-27): Compiling rpc.github.request
2020-04-06 21:56:54.075338 (Thread-27): finished collecting timing info
2020-04-06 21:56:54.075669 (Thread-27): finished collecting timing info
2020-04-06 21:56:54.215342 (Thread-28): handling poll request
2020-04-06 21:56:54.215854 (Thread-28): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80914518>]}
2020-04-06 21:56:54.220415 (Thread-28): sending response (<Response 6200 bytes [200 OK]>) to 10.0.23.84
2020-04-06 21:57:00.428761 (Thread-29): handling run_sql request
2020-04-06 21:57:00.431619 (Thread-30): handling ps request
2020-04-06 21:57:00.431827 (Thread-29): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812f7160>]}
2020-04-06 21:57:00.432286 (Thread-30): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80921240>]}
2020-04-06 21:57:00.434878 (Thread-30): sending response (<Response 403 bytes [200 OK]>) to 10.0.46.192
2020-04-06 21:57:00.441161 (Thread-29): sending response (<Response 133 bytes [200 OK]>) to 10.0.9.254
2020-04-06 21:57:00.456126 (Thread-29): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:57:00.456697 (Thread-29): Opening a new connection, currently in state init
2020-04-06 21:57:00.463089 (Thread-29): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:57:00.463996 (Thread-31): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:57:00.464094 (Thread-31): Opening a new connection, currently in state init
2020-04-06 21:57:00.464194 (Thread-31): Compiling rpc.github.request
2020-04-06 21:57:00.477097 (Thread-31): finished collecting timing info
2020-04-06 21:57:00.478420 (Thread-31): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
FROM
  bigquery-public-data.github_repos.commits
limit 100
2020-04-06 21:57:00.642968 (Thread-31): handling poll request
2020-04-06 21:57:00.643860 (Thread-31): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812f7160>]}
2020-04-06 21:57:00.646316 (Thread-31): sending response (<Response 3480 bytes [200 OK]>) to 10.0.41.194
2020-04-06 21:57:01.344996 (Thread-32): handling poll request
2020-04-06 21:57:01.345504 (Thread-32): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809140b8>]}
2020-04-06 21:57:01.374028 (Thread-32): sending response (<Response 3481 bytes [200 OK]>) to 10.0.39.229
2020-04-06 21:57:02.048901 (Thread-33): handling poll request
2020-04-06 21:57:02.049424 (Thread-33): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80914550>]}
2020-04-06 21:57:02.051299 (Thread-33): sending response (<Response 3481 bytes [200 OK]>) to 10.0.7.248
2020-04-06 21:57:02.094802 (Thread-31): finished collecting timing info
2020-04-06 21:57:02.728946 (Thread-34): handling poll request
2020-04-06 21:57:02.729456 (Thread-34): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81251b38>]}
2020-04-06 21:57:02.734764 (Thread-34): sending response (<Response 58850 bytes [200 OK]>) to 10.0.23.84
2020-04-06 21:58:39.498543 (Thread-35): handling run_sql request
2020-04-06 21:58:39.500696 (Thread-35): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809219b0>]}
2020-04-06 21:58:39.506829 (Thread-35): sending response (<Response 133 bytes [200 OK]>) to 10.0.23.84
2020-04-06 21:58:39.525316 (Thread-35): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:58:39.525924 (Thread-35): Opening a new connection, currently in state init
2020-04-06 21:58:39.537528 (Thread-35): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:58:39.538676 (Thread-36): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:58:39.538823 (Thread-36): Opening a new connection, currently in state init
2020-04-06 21:58:39.538960 (Thread-36): Compiling rpc.github.request
2020-04-06 21:58:39.556338 (Thread-36): finished collecting timing info
2020-04-06 21:58:39.560178 (Thread-36): handling ps request
2020-04-06 21:58:39.557702 (Thread-36): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */

limit 100
2020-04-06 21:58:39.561178 (Thread-36): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c808cc1d0>]}
2020-04-06 21:58:39.563609 (Thread-36): sending response (<Response 398 bytes [200 OK]>) to 10.0.46.192
2020-04-06 21:58:39.674276 (Thread-37): handling poll request
2020-04-06 21:58:39.674891 (Thread-37): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80944fd0>]}
2020-04-06 21:58:39.677398 (Thread-37): sending response (<Response 3133 bytes [200 OK]>) to 10.0.7.248
2020-04-06 21:58:39.825709 (Thread-36): finished collecting timing info
2020-04-06 21:58:39.826392 (Thread-36): Got an exception: Database Error
  Syntax error: Unexpected keyword LIMIT at [3:1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword LIMIT at [3:1]

(job ID: 21f28646-3de9-4106-a8aa-fa60e62b57d9)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:
   3:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unexpected keyword LIMIT at [3:1]
2020-04-06 21:58:39.828733 (Thread-36): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword LIMIT at [3:1]', 'raw_sql': '\nlimit 100', 'compiled_sql': '\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword LIMIT at [3:1]', 'raw_sql': '\nlimit 100', 'compiled_sql': '\nlimit 100', 'tags': None}, None)
2020-04-06 21:58:40.385101 (Thread-38): handling poll request
2020-04-06 21:58:40.385611 (Thread-38): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8091e438>]}
2020-04-06 21:58:40.387732 (Thread-38): sending response (<Response 8898 bytes [200 OK]>) to 10.0.41.194
2020-04-06 21:59:34.304383 (Thread-39): handling run_sql request
2020-04-06 21:59:34.306957 (Thread-39): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80914860>]}
2020-04-06 21:59:34.308677 (Thread-40): handling ps request
2020-04-06 21:59:34.314917 (Thread-39): sending response (<Response 133 bytes [200 OK]>) to 10.0.9.254
2020-04-06 21:59:34.315622 (Thread-40): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81251860>]}
2020-04-06 21:59:34.318662 (Thread-40): sending response (<Response 398 bytes [200 OK]>) to 10.0.39.229
2020-04-06 21:59:34.328899 (Thread-39): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:59:34.329422 (Thread-39): Opening a new connection, currently in state init
2020-04-06 21:59:34.336229 (Thread-39): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 21:59:34.337069 (Thread-41): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 21:59:34.337187 (Thread-41): Opening a new connection, currently in state init
2020-04-06 21:59:34.337325 (Thread-41): Compiling rpc.github.request
2020-04-06 21:59:34.350267 (Thread-41): finished collecting timing info
2020-04-06 21:59:34.351672 (Thread-41): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
FROM
  bigquery-public-data.github_repos.commits
limit 100
2020-04-06 21:59:34.481052 (Thread-41): handling poll request
2020-04-06 21:59:34.481565 (Thread-41): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c81c7c0b8>]}
2020-04-06 21:59:34.483525 (Thread-41): sending response (<Response 3481 bytes [200 OK]>) to 10.0.7.248
2020-04-06 21:59:35.158067 (Thread-42): handling poll request
2020-04-06 21:59:35.158623 (Thread-42): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c809c4cc0>]}
2020-04-06 21:59:35.160446 (Thread-42): sending response (<Response 3480 bytes [200 OK]>) to 10.0.41.194
2020-04-06 21:59:35.310046 (Thread-41): finished collecting timing info
2020-04-06 21:59:35.850749 (Thread-43): handling poll request
2020-04-06 21:59:35.851253 (Thread-43): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80944588>]}
2020-04-06 21:59:35.856572 (Thread-43): sending response (<Response 58850 bytes [200 OK]>) to 10.0.29.175
2020-04-06 21:59:39.950354 (Thread-44): Got an acceptable cached parse result
2020-04-06 21:59:40.002442 (Thread-44): Acquiring new bigquery connection "model.github.commits".
2020-04-06 21:59:40.002633 (Thread-44): Opening a new connection, currently in state init
2020-04-06 21:59:40.224624 (Thread-44): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.github.dw
- models.github.stage

2020-04-06 21:59:40.225384 (Thread-45): handling status request
2020-04-06 21:59:40.227056 (Thread-45): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73feb518>]}
2020-04-06 21:59:40.228912 (Thread-45): sending response (<Response 1452 bytes [200 OK]>) to 10.0.39.229
2020-04-06 22:02:19.158904 (Thread-46): handling run_sql request
2020-04-06 22:02:19.166563 (Thread-46): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c813bd2b0>]}
2020-04-06 22:02:19.168510 (Thread-46): Connection 'model.github.commits' was properly closed.
2020-04-06 22:02:19.191153 (Thread-46): sending response (<Response 133 bytes [200 OK]>) to 10.0.27.197
2020-04-06 22:02:19.198209 (Thread-47): handling ps request
2020-04-06 22:02:19.198901 (Thread-47): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73fc7f98>]}
2020-04-06 22:02:19.201646 (Thread-47): sending response (<Response 399 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:02:19.265855 (Thread-46): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:02:19.279829 (Thread-46): Opening a new connection, currently in state init
2020-04-06 22:02:19.322879 (Thread-46): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:02:19.324065 (Thread-47): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:02:19.324214 (Thread-47): Opening a new connection, currently in state init
2020-04-06 22:02:19.324354 (Thread-47): Compiling rpc.github.request
2020-04-06 22:02:19.418421 (Thread-47): finished collecting timing info
2020-04-06 22:02:19.420141 (Thread-47): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  unnest(repo_name) repo_name
  bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:02:19.458841 (Thread-48): handling poll request
2020-04-06 22:02:19.459687 (Thread-48): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73fc7f98>]}
2020-04-06 22:02:19.463898 (Thread-48): sending response (<Response 3496 bytes [200 OK]>) to 10.0.5.66
2020-04-06 22:02:19.867841 (Thread-47): finished collecting timing info
2020-04-06 22:02:19.868734 (Thread-47): Got an exception: Database Error
  Syntax error: Unexpected keyword UNNEST at [14:3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword UNNEST at [14:3]

(job ID: 2decb37e-c8dd-454d-8cd0-a2613dce48e1)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:SELECT
   3:  commit,
   4:  tree,
   5:  parent,
   6:  author.name author_name,
   7:  author.email author_email,
   8:  author.date.seconds author_date_seconds,
   9:  committer.name committer_name,
  10:  committer.email committer_email,
  11:  committer.date.seconds committer_date_seconds,
  12:  subject,
  13:  message,
  14:  unnest(repo_name) repo_name
  15:  bigquery-public-data.github_repos.commits
  16:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unexpected keyword UNNEST at [14:3]
2020-04-06 22:02:19.875853 (Thread-47): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword UNNEST at [14:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword UNNEST at [14:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
2020-04-06 22:02:20.266841 (Thread-49): handling poll request
2020-04-06 22:02:20.270040 (Thread-49): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c813aa080>]}
2020-04-06 22:02:20.271348 (Thread-49): sending response (<Response 11902 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:05:22.951052 (Thread-50): Got an acceptable cached parse result
2020-04-06 22:05:23.023678 (Thread-50): Acquiring new bigquery connection "model.github.commits".
2020-04-06 22:05:23.023900 (Thread-50): Opening a new connection, currently in state init
2020-04-06 22:05:23.222310 (Thread-51): handling status request
2020-04-06 22:05:23.238865 (Thread-51): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e9c320>]}
2020-04-06 22:05:23.240061 (Thread-51): sending response (<Response 182 bytes [200 OK]>) to 10.0.46.192
2020-04-06 22:05:23.324710 (Thread-50): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.github.dw
- models.github.stage

2020-04-06 22:05:24.437569 (Thread-52): handling status request
2020-04-06 22:05:24.438445 (Thread-52): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8001f2e8>]}
2020-04-06 22:05:24.440265 (Thread-52): sending response (<Response 1452 bytes [200 OK]>) to 10.0.9.254
2020-04-06 22:05:36.266073 (Thread-53): handling status request
2020-04-06 22:05:36.268571 (Thread-53): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8001f2e8>]}
2020-04-06 22:05:36.270362 (Thread-53): sending response (<Response 1452 bytes [200 OK]>) to 10.0.23.84
2020-04-06 22:05:40.079975 (Thread-54): handling run_sql request
2020-04-06 22:05:40.080495 (Thread-54): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8001f7b8>]}
2020-04-06 22:05:40.081873 (Thread-54): Connection 'model.github.commits' was properly closed.
2020-04-06 22:05:40.087010 (Thread-54): sending response (<Response 133 bytes [200 OK]>) to 10.0.5.66
2020-04-06 22:05:40.103480 (Thread-54): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:05:40.104004 (Thread-54): Opening a new connection, currently in state init
2020-04-06 22:05:40.110611 (Thread-54): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:05:40.111428 (Thread-55): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:05:40.111539 (Thread-55): Opening a new connection, currently in state init
2020-04-06 22:05:40.111644 (Thread-55): Compiling rpc.github.request
2020-04-06 22:05:40.126507 (Thread-55): finished collecting timing info
2020-04-06 22:05:40.127932 (Thread-55): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  unnest(repo_name) repo_name
  bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:05:40.132852 (Thread-55): handling ps request
2020-04-06 22:05:40.133381 (Thread-55): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8003b9b0>]}
2020-04-06 22:05:40.135222 (Thread-55): sending response (<Response 397 bytes [200 OK]>) to 10.0.46.192
2020-04-06 22:05:40.324990 (Thread-56): handling poll request
2020-04-06 22:05:40.325718 (Thread-56): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8003b860>]}
2020-04-06 22:05:40.328339 (Thread-56): sending response (<Response 3498 bytes [200 OK]>) to 10.0.7.248
2020-04-06 22:05:40.394757 (Thread-55): finished collecting timing info
2020-04-06 22:05:40.395748 (Thread-55): Got an exception: Database Error
  Syntax error: Unexpected keyword UNNEST at [14:3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword UNNEST at [14:3]

(job ID: b8891ea9-59a7-4a4d-8a39-ec3b0ffa7238)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:SELECT
   3:  commit,
   4:  tree,
   5:  parent,
   6:  author.name author_name,
   7:  author.email author_email,
   8:  author.date.seconds author_date_seconds,
   9:  committer.name committer_name,
  10:  committer.email committer_email,
  11:  committer.date.seconds committer_date_seconds,
  12:  subject,
  13:  message,
  14:  unnest(repo_name) repo_name
  15:  bigquery-public-data.github_repos.commits
  16:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unexpected keyword UNNEST at [14:3]
2020-04-06 22:05:40.399222 (Thread-55): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword UNNEST at [14:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword UNNEST at [14:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  unnest(repo_name) repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
2020-04-06 22:05:41.323597 (Thread-57): handling poll request
2020-04-06 22:05:41.324432 (Thread-57): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c80030e48>]}
2020-04-06 22:05:41.325751 (Thread-57): sending response (<Response 11907 bytes [200 OK]>) to 10.0.27.197
2020-04-06 22:05:41.714270 (Thread-58): Got an acceptable cached parse result
2020-04-06 22:05:42.031020 (Thread-58): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.github.dw
- models.github.stage

2020-04-06 22:05:42.062752 (Thread-59): handling status request
2020-04-06 22:05:42.071151 (Thread-59): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73eccdd8>]}
2020-04-06 22:05:42.072509 (Thread-59): sending response (<Response 882 bytes [200 OK]>) to 10.0.23.84
2020-04-06 22:05:53.963905 (Thread-60): handling run_sql request
2020-04-06 22:05:53.966334 (Thread-60): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73eccdd8>]}
2020-04-06 22:05:53.974604 (Thread-60): sending response (<Response 133 bytes [200 OK]>) to 10.0.23.84
2020-04-06 22:05:53.983252 (Thread-61): handling ps request
2020-04-06 22:05:53.984067 (Thread-61): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73df3c50>]}
2020-04-06 22:05:53.986888 (Thread-61): sending response (<Response 398 bytes [200 OK]>) to 10.0.46.192
2020-04-06 22:05:53.991680 (Thread-60): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:05:53.992234 (Thread-60): Opening a new connection, currently in state init
2020-04-06 22:05:53.999964 (Thread-60): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:05:54.001072 (Thread-61): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:05:54.001230 (Thread-61): Opening a new connection, currently in state init
2020-04-06 22:05:54.001834 (Thread-61): Compiling rpc.github.request
2020-04-06 22:05:54.018256 (Thread-61): finished collecting timing info
2020-04-06 22:05:54.019860 (Thread-61): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
  bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:05:54.166619 (Thread-62): handling poll request
2020-04-06 22:05:54.167120 (Thread-62): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73df3c50>]}
2020-04-06 22:05:54.169853 (Thread-62): sending response (<Response 3483 bytes [200 OK]>) to 10.0.41.194
2020-04-06 22:05:54.291567 (Thread-61): finished collecting timing info
2020-04-06 22:05:54.292210 (Thread-61): Got an exception: Database Error
  Syntax error: Unexpected "-" at [15:11]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected "-" at [15:11]

(job ID: 4923a3cd-700f-4777-b51a-000cd0d814bf)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:SELECT
   3:  commit,
   4:  tree,
   5:  parent,
   6:  author.name author_name,
   7:  author.email author_email,
   8:  author.date.seconds author_date_seconds,
   9:  committer.name committer_name,
  10:  committer.email committer_email,
  11:  committer.date.seconds committer_date_seconds,
  12:  subject,
  13:  message,
  14:  repo_name
  15:  bigquery-public-data.github_repos.commits
  16:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unexpected "-" at [15:11]
2020-04-06 22:05:54.294822 (Thread-61): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected "-" at [15:11]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected "-" at [15:11]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name\n  bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
2020-04-06 22:05:54.849529 (Thread-63): handling poll request
2020-04-06 22:05:54.850047 (Thread-63): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73ecca58>]}
2020-04-06 22:05:54.851056 (Thread-63): sending response (<Response 11718 bytes [200 OK]>) to 10.0.27.197
2020-04-06 22:06:11.663380 (Thread-64): handling run_sql request
2020-04-06 22:06:11.665769 (Thread-64): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73ef3a20>]}
2020-04-06 22:06:11.672423 (Thread-64): sending response (<Response 133 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:06:11.688013 (Thread-64): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:11.696765 (Thread-65): handling ps request
2020-04-06 22:06:11.688549 (Thread-64): Opening a new connection, currently in state init
2020-04-06 22:06:11.697690 (Thread-65): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73ef3a20>]}
2020-04-06 22:06:11.695523 (Thread-64): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:06:11.696584 (Thread-65): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:11.696736 (Thread-65): Opening a new connection, currently in state init
2020-04-06 22:06:11.696887 (Thread-65): Compiling rpc.github.request
2020-04-06 22:06:11.713355 (Thread-65): finished collecting timing info
2020-04-06 22:06:11.714844 (Thread-65): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
from bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:06:11.729546 (Thread-65): sending response (<Response 399 bytes [200 OK]>) to 10.0.46.192
2020-04-06 22:06:11.855460 (Thread-66): handling poll request
2020-04-06 22:06:11.855952 (Thread-66): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73f39cf8>]}
2020-04-06 22:06:11.857827 (Thread-66): sending response (<Response 3489 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:06:12.569804 (Thread-67): handling poll request
2020-04-06 22:06:12.570420 (Thread-67): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73dc36a0>]}
2020-04-06 22:06:12.572264 (Thread-67): sending response (<Response 3489 bytes [200 OK]>) to 10.0.46.192
2020-04-06 22:06:13.046824 (Thread-65): finished collecting timing info
2020-04-06 22:06:13.218148 (Thread-68): handling poll request
2020-04-06 22:06:13.218664 (Thread-68): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73f396a0>]}
2020-04-06 22:06:13.224649 (Thread-68): sending response (<Response 58844 bytes [200 OK]>) to 10.0.7.248
2020-04-06 22:06:30.056827 (Thread-69): handling ps request
2020-04-06 22:06:30.059259 (Thread-69): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73f396a0>]}
2020-04-06 22:06:30.060144 (Thread-69): sending response (<Response 100 bytes [200 OK]>) to 10.0.23.84
2020-04-06 22:06:30.072156 (Thread-70): handling run_sql request
2020-04-06 22:06:30.072530 (Thread-70): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73f393c8>]}
2020-04-06 22:06:30.079028 (Thread-70): sending response (<Response 133 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:06:30.094705 (Thread-70): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:30.095236 (Thread-70): Opening a new connection, currently in state init
2020-04-06 22:06:30.102454 (Thread-70): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:06:30.103410 (Thread-71): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:30.103522 (Thread-71): Opening a new connection, currently in state init
2020-04-06 22:06:30.103621 (Thread-71): Compiling rpc.github.request
2020-04-06 22:06:30.116856 (Thread-71): finished collecting timing info
2020-04-06 22:06:30.118455 (Thread-71): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name,
  unnest(repo_name)
from bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:06:30.278015 (Thread-71): handling poll request
2020-04-06 22:06:30.278680 (Thread-71): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73f393c8>]}
2020-04-06 22:06:30.281162 (Thread-71): sending response (<Response 3510 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:06:30.345824 (Thread-71): finished collecting timing info
2020-04-06 22:06:30.346504 (Thread-71): Got an exception: Database Error
  Syntax error: Unexpected keyword UNNEST at [15:3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword UNNEST at [15:3]

(job ID: 182d4542-cdb2-4272-85da-0068353810b0)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:SELECT
   3:  commit,
   4:  tree,
   5:  parent,
   6:  author.name author_name,
   7:  author.email author_email,
   8:  author.date.seconds author_date_seconds,
   9:  committer.name committer_name,
  10:  committer.email committer_email,
  11:  committer.date.seconds committer_date_seconds,
  12:  subject,
  13:  message,
  14:  repo_name,
  15:  unnest(repo_name)
  16:from bigquery-public-data.github_repos.commits
  17:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Syntax error: Unexpected keyword UNNEST at [15:3]
2020-04-06 22:06:30.348753 (Thread-71): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword UNNEST at [15:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  unnest(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  unnest(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Syntax error: Unexpected keyword UNNEST at [15:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  unnest(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  unnest(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
2020-04-06 22:06:30.940596 (Thread-72): handling poll request
2020-04-06 22:06:30.941090 (Thread-72): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73ef9be0>]}
2020-04-06 22:06:30.941987 (Thread-72): sending response (<Response 11978 bytes [200 OK]>) to 10.0.13.188
2020-04-06 22:06:41.978262 (Thread-73): handling ps request
2020-04-06 22:06:41.979262 (Thread-74): handling run_sql request
2020-04-06 22:06:41.980973 (Thread-73): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e320b8>]}
2020-04-06 22:06:41.981433 (Thread-74): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e27c50>]}
2020-04-06 22:06:41.982549 (Thread-73): sending response (<Response 100 bytes [200 OK]>) to 10.0.5.66
2020-04-06 22:06:41.990548 (Thread-74): sending response (<Response 133 bytes [200 OK]>) to 10.0.29.175
2020-04-06 22:06:42.005660 (Thread-74): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:42.006203 (Thread-74): Opening a new connection, currently in state init
2020-04-06 22:06:42.012983 (Thread-74): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:06:42.013821 (Thread-75): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:42.014059 (Thread-75): Opening a new connection, currently in state init
2020-04-06 22:06:42.014204 (Thread-75): Compiling rpc.github.request
2020-04-06 22:06:42.027476 (Thread-75): finished collecting timing info
2020-04-06 22:06:42.029100 (Thread-75): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name,
  flatten(repo_name)
from bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:06:42.199673 (Thread-75): handling poll request
2020-04-06 22:06:42.200233 (Thread-75): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e27c50>]}
2020-04-06 22:06:42.202775 (Thread-75): sending response (<Response 3512 bytes [200 OK]>) to 10.0.46.192
2020-04-06 22:06:42.453596 (Thread-75): finished collecting timing info
2020-04-06 22:06:42.454300 (Thread-75): Got an exception: Database Error
  Function not found: flatten at [15:3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 80, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 212, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 339, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Function not found: flatten at [15:3]

(job ID: 5c63bea8-2951-4bcf-bb88-18fc8d25e14f)

                                                   -----Query Job SQL Follows-----                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:/* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
   2:SELECT
   3:  commit,
   4:  tree,
   5:  parent,
   6:  author.name author_name,
   7:  author.email author_email,
   8:  author.date.seconds author_date_seconds,
   9:  committer.name committer_name,
  10:  committer.email committer_email,
  11:  committer.date.seconds committer_date_seconds,
  12:  subject,
  13:  message,
  14:  repo_name,
  15:  flatten(repo_name)
  16:from bigquery-public-data.github_repos.commits
  17:limit 100
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 221, in execute
    query_job, iterator = self.raw_execute(sql, fetch=fetch)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 214, in raw_execute
    query_job, iterator = self._retry_and_handle(msg=sql, conn=conn, fn=fn)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 350, in _retry_and_handle
    deadline=None)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 84, in exception_handler
    self.handle_error(e, message)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/bigquery/connections.py", line 72, in handle_error
    raise DatabaseException(error_msg)
dbt.exceptions.DatabaseException: Database Error
  Function not found: flatten at [15:3]
2020-04-06 22:06:42.457388 (Thread-75): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Function not found: flatten at [15:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  flatten(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  flatten(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 239, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  Function not found: flatten at [15:3]', 'raw_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  flatten(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'compiled_sql': 'SELECT\n  commit,\n  tree,\n  parent,\n  author.name author_name,\n  author.email author_email,\n  author.date.seconds author_date_seconds,\n  committer.name committer_name,\n  committer.email committer_email,\n  committer.date.seconds committer_date_seconds,\n  subject,\n  message,\n  repo_name,\n  flatten(repo_name)\nfrom bigquery-public-data.github_repos.commits\nlimit 100', 'tags': None}, None)
2020-04-06 22:06:42.889945 (Thread-76): handling poll request
2020-04-06 22:06:42.890899 (Thread-76): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73ef9be0>]}
2020-04-06 22:06:42.891869 (Thread-76): sending response (<Response 11914 bytes [200 OK]>) to 10.0.39.229
2020-04-06 22:06:49.089793 (Thread-77): handling run_sql request
2020-04-06 22:06:49.092193 (Thread-77): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73f39198>]}
2020-04-06 22:06:49.099463 (Thread-77): sending response (<Response 133 bytes [200 OK]>) to 10.0.9.254
2020-04-06 22:06:49.102137 (Thread-78): handling ps request
2020-04-06 22:06:49.115240 (Thread-78): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e317b8>]}
2020-04-06 22:06:49.117525 (Thread-78): sending response (<Response 398 bytes [200 OK]>) to 10.0.5.66
2020-04-06 22:06:49.118987 (Thread-77): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:49.126270 (Thread-77): Opening a new connection, currently in state init
2020-04-06 22:06:49.146216 (Thread-77): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-06 22:06:49.147502 (Thread-78): Acquiring new bigquery connection "rpc.github.request".
2020-04-06 22:06:49.147662 (Thread-78): Opening a new connection, currently in state init
2020-04-06 22:06:49.147855 (Thread-78): Compiling rpc.github.request
2020-04-06 22:06:49.169321 (Thread-78): finished collecting timing info
2020-04-06 22:06:49.170762 (Thread-78): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
from bigquery-public-data.github_repos.commits
limit 100
2020-04-06 22:06:49.302849 (Thread-79): handling poll request
2020-04-06 22:06:49.303368 (Thread-79): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e32278>]}
2020-04-06 22:06:49.305300 (Thread-79): sending response (<Response 3486 bytes [200 OK]>) to 10.0.41.194
2020-04-06 22:06:50.002970 (Thread-80): handling poll request
2020-04-06 22:06:50.003481 (Thread-80): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e2b6a0>]}
2020-04-06 22:06:50.005299 (Thread-80): sending response (<Response 3486 bytes [200 OK]>) to 10.0.9.254
2020-04-06 22:06:50.433249 (Thread-78): finished collecting timing info
2020-04-06 22:06:50.690545 (Thread-81): handling poll request
2020-04-06 22:06:50.691034 (Thread-81): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e2b198>]}
2020-04-06 22:06:50.696449 (Thread-81): sending response (<Response 58841 bytes [200 OK]>) to 10.0.29.175
2020-04-07 00:39:37.707722 (Thread-82): handling run_sql request
2020-04-07 00:39:37.719744 (Thread-83): handling ps request
2020-04-07 00:39:37.732363 (Thread-82): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c8003bc88>]}
2020-04-07 00:39:37.732840 (Thread-83): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e2bc50>]}
2020-04-07 00:39:37.735160 (Thread-83): sending response (<Response 404 bytes [200 OK]>) to 10.0.29.175
2020-04-07 00:39:37.742990 (Thread-82): sending response (<Response 133 bytes [200 OK]>) to 10.0.41.194
2020-04-07 00:39:37.758003 (Thread-82): Acquiring new bigquery connection "rpc.github.request".
2020-04-07 00:39:37.758564 (Thread-82): Opening a new connection, currently in state init
2020-04-07 00:39:37.770047 (Thread-82): Found 1 model, 0 tests, 0 snapshots, 0 analyses, 141 macros, 0 operations, 0 seed files, 0 sources
2020-04-07 00:39:37.770999 (Thread-84): Acquiring new bigquery connection "rpc.github.request".
2020-04-07 00:39:37.771108 (Thread-84): Opening a new connection, currently in state init
2020-04-07 00:39:37.771246 (Thread-84): Compiling rpc.github.request
2020-04-07 00:39:37.784549 (Thread-84): finished collecting timing info
2020-04-07 00:39:37.785956 (Thread-84): On rpc.github.request: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "user", "target_name": "default", "node_id": "rpc.github.request"} */
SELECT
  commit,
  tree,
  parent,
  author.name author_name,
  author.email author_email,
  author.date.seconds author_date_seconds,
  committer.name committer_name,
  committer.email committer_email,
  committer.date.seconds committer_date_seconds,
  subject,
  message,
  repo_name
from bigquery-public-data.github_repos.commits
limit 100
2020-04-07 00:39:37.920266 (Thread-84): handling poll request
2020-04-07 00:39:37.920822 (Thread-84): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e2bfd0>]}
2020-04-07 00:39:37.923350 (Thread-84): sending response (<Response 3489 bytes [200 OK]>) to 10.0.23.84
2020-04-07 00:39:38.573707 (Thread-85): handling poll request
2020-04-07 00:39:38.574268 (Thread-85): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73df32e8>]}
2020-04-07 00:39:38.576084 (Thread-85): sending response (<Response 3488 bytes [200 OK]>) to 10.0.13.188
2020-04-07 00:39:39.019890 (Thread-84): finished collecting timing info
2020-04-07 00:39:39.272637 (Thread-86): handling poll request
2020-04-07 00:39:39.273141 (Thread-86): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73fe8f28>]}
2020-04-07 00:39:39.278641 (Thread-86): sending response (<Response 58844 bytes [200 OK]>) to 10.0.46.192
2020-04-07 00:39:58.778152 (Thread-87): handling status request
2020-04-07 00:39:58.780224 (Thread-87): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e87dd8>]}
2020-04-07 00:39:58.781248 (Thread-87): sending response (<Response 882 bytes [200 OK]>) to 10.0.41.194
2020-04-07 00:40:03.972795 (Thread-88): Got an acceptable cached parse result
2020-04-07 00:40:04.132683 (Thread-89): handling status request
2020-04-07 00:40:04.134282 (Thread-89): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73d93400>]}
2020-04-07 00:40:04.135104 (Thread-89): sending response (<Response 182 bytes [200 OK]>) to 10.0.9.254
2020-04-07 00:40:04.340323 (Thread-88): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.github.dw
- models.github.stage

2020-04-07 00:40:05.328982 (Thread-90): handling status request
2020-04-07 00:40:05.329525 (Thread-90): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73ed8e80>]}
2020-04-07 00:40:05.330612 (Thread-90): sending response (<Response 882 bytes [200 OK]>) to 10.0.41.194
2020-04-07 00:42:15.901956 (Thread-91): Got an acceptable cached parse result
2020-04-07 00:42:15.948711 (Thread-91): Acquiring new bigquery connection "model.github.commits".
2020-04-07 00:42:15.948888 (Thread-91): Opening a new connection, currently in state init
2020-04-07 00:42:16.068002 (Thread-92): handling status request
2020-04-07 00:42:16.071957 (Thread-92): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c73e12a20>]}
2020-04-07 00:42:16.073031 (Thread-92): sending response (<Response 182 bytes [200 OK]>) to 10.0.13.188
2020-04-07 00:42:16.265841 (Thread-91): WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.github.dw
- models.github.stage

2020-04-07 00:42:17.238628 (Thread-93): handling status request
2020-04-07 00:42:17.239230 (Thread-93): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812c5ac8>]}
2020-04-07 00:42:17.240593 (Thread-93): sending response (<Response 1452 bytes [200 OK]>) to 10.0.5.66
2020-04-07 00:42:25.859427 (Thread-94): handling status request
2020-04-07 00:42:25.861789 (Thread-94): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'a1151651-bcba-411f-9e5a-8f0bf6b69223', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3c812c5780>]}
2020-04-07 00:42:25.863012 (Thread-94): sending response (<Response 1452 bytes [200 OK]>) to 10.0.41.194
